apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.am.service.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.am.service.externalPort }}
    targetPort: {{ .Values.am.service.internalPort }}
    protocol: TCP
    name: {{ .Values.am.service.name }}
  - port: 8243
    targetPort: 8243
    protocol: TCP
    name: am-portal

  selector:
    app: {{.Values.am.name}}